# Generated by Django 3.2.4 on 2022-03-30 06:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='DEPARTMENT')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='TITLE')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='USER ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='FIRST NAME')),
                ('middlename', models.CharField(max_length=50, verbose_name='MIDDLE NAME')),
                ('lastname', models.CharField(max_length=50, verbose_name='LAST NAME')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('birthday', models.DateField(verbose_name='BIRTHDAY')),
                ('province', models.CharField(max_length=50, verbose_name='PROVINCE')),
                ('city', models.CharField(max_length=50, verbose_name='CITY')),
                ('street', models.CharField(max_length=50, verbose_name='STREET')),
                ('zip', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^([\\s\\d]+)$', 'Only numbers are allowed.')], verbose_name='ZIP')),
                ('contact', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^([\\s\\d]+)$', 'Only numbers are allowed.')], verbose_name='CONTACT')),
                ('hireday', models.DateField(verbose_name='HIREDAY')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='START DATE')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='END DATE')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.department', verbose_name='DEPARTMENT')),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.jobrole', verbose_name='JOB ROLE')),
            ],
        ),
    ]
