# Generated by Django 3.2.4 on 2022-03-30 07:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='DEPARTMENT')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'tbl_department',
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='TITLE')),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
                'db_table': 'tbl_job_role',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='FIRST NAME')),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True, verbose_name='MIDDLE INITIAL')),
                ('lastname', models.CharField(max_length=50, verbose_name='LAST NAME')),
                ('name_suffix', models.CharField(blank=True, choices=[('SR.', 'SENIOR'), ('JR.', 'JUNIOR'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=10, null=True, verbose_name='Suffix')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('birthday', models.DateField(verbose_name='BIRTHDAY')),
                ('fullname', models.CharField(max_length=255, verbose_name='Fullname')),
                ('province', models.CharField(max_length=50, verbose_name='PROVINCE')),
                ('city', models.CharField(max_length=50, verbose_name='CITY')),
                ('barangay', models.CharField(max_length=50, verbose_name='BARANGAY')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='STREET')),
                ('zip', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^([\\s\\d]+)$', 'Only numbers are allowed.')], verbose_name='ZIP')),
                ('contact', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^([\\s\\d]+)$', 'Only numbers are allowed.')], verbose_name='CONTACT')),
                ('hireday', models.DateField(verbose_name='HIREDAY')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='START DATE')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='END DATE')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.department', verbose_name='DEPARTMENT')),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.jobrole', verbose_name='JOB ROLE')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'tbl_employee',
            },
        ),
    ]
