# Generated by Django 3.2.4 on 2022-03-30 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_employee_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP ADDRESS')),
                ('port', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^([\\s\\d]+)$', 'Only numbers are allowed.')], verbose_name='PORT')),
                ('machine_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='MACHINE NAME')),
            ],
        ),
    ]
