# Generated by Django 3.2.4 on 2022-03-31 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checktime', models.DateTimeField(unique=True, verbose_name='Check Time')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Check In/Out',
                'verbose_name_plural': 'Employee Check In/Out',
                'db_table': 'tbl_employee_check_in_out',
            },
        ),
    ]
