# Generated by Django 3.2.4 on 2022-03-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecheckinout',
            name='checktime',
            field=models.DateTimeField(unique=True, verbose_name='Check Time'),
        ),
    ]
